# -*- coding: utf-8 -*-
"""作業1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Gvu33-FH6Ls97U6gmL_HZeQeXum4XQd
"""

x=5
print("f變數x的值是:{x}")
print(f"變數x的記憶體地址是:{id(x)}")